import sys
import os

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))

from app.db.database import SessionLocal
import app.models
from app.models.school import School
from app.models.program import Program
from sqlalchemy import text

SEED_DATA = [
    {
        "school": {
            "name": "The ICT University",
            "location": "Messassi, Yaounde, Centre Region, Cameroon",
            "description": "Premier US-accredited private university in Central Africa delivering cutting-edge, ICT-driven education, innovation, and global entrepreneurship training.",
            "website_url": "https://ictuniversity.edu.cm",
            "logo_url": "https://ictuniversity.edu.cm/wp-content/uploads/2021/04/ict-logo.png",
            "contact_email": "admissions@ictuniversity.edu.cm",
            "application_deadline": "October 31, 2026",
            "rolling_admission": True,
            "city": "Yaoundé",
            "institution_type": "ipes",
            "data_source_url": "https://ictuniversity.edu.cm",
        },
        "programs": [
            {
                "field_of_study": "Software Engineering",
                "degree_type": "Bachelor",
                "tuition_fee": "730,000 FCFA / year",
                "duration": "3 years",
                "language_of_instruction": "English",
                "delivery_mode": "On-Campus",
                "admission_requirements": "GCE Advanced Level (minimum 2 papers with C in Math/Computer Science) or Baccalaureat C/D/TI.",
                "required_documents": "GCE/Bacc transcript, National ID card copy, 2 passport photos, Birth Certificate.",
                "application_deadline": "October 31, 2026",
                "class_size": 60,
                "description": "Comprehensive software engineering curriculum covering full-stack web, mobile architectures, algorithms, cloud systems, and agile dev practices.",
            },
            {
                "field_of_study": "Cybersecurity & Digital Forensics",
                "degree_type": "Bachelor",
                "tuition_fee": "780,000 FCFA / year",
                "duration": "3 years",
                "language_of_instruction": "English",
                "delivery_mode": "On-Campus",
                "admission_requirements": "GCE Advanced Level with 2 passes in science subjects or Baccalaureat C/D/TI/E.",
                "required_documents": "Academic transcripts, Proof of English proficiency, Copy of CNI/Passport, Recommendation letter.",
                "application_deadline": "October 31, 2026",
                "class_size": 45,
                "description": "Advanced defensive security, network penetration testing, cryptography, incident response, digital evidence collection, and cloud security.",
            },
            {
                "field_of_study": "Information Systems & Big Data Analytics",
                "degree_type": "Master",
                "tuition_fee": "1,100,000 FCFA / year",
                "duration": "2 years",
                "language_of_instruction": "English",
                "delivery_mode": "Hybrid",
                "admission_requirements": "Bachelor degree in Computer Science, Software Engineering, Mathematics, or related STEM discipline (min GPA 2.8/4.0).",
                "required_documents": "Certified degree certificate, official transcripts, CV/Resume, Statement of Purpose, 2 academic references.",
                "application_deadline": "November 15, 2026",
                "class_size": 35,
                "description": "Postgraduate training focusing on big data pipelines, distributed systems, machine learning engineering, enterprise BI architectures, and cloud analytics.",
            },
        ],
    },
    {
        "school": {
            "name": "National Advanced School of Engineering (Polytech Yaounde)",
            "location": "Melan, Yaounde, Centre Region, Cameroon",
            "description": "Cameroon's premier public grande ecole d'ingenieurs affiliated with University of Yaounde I, training elite engineers and innovators since 1971.",
            "website_url": "https://polytechnique.cm",
            "logo_url": "https://polytechnique.cm/wp-content/themes/enspy/images/logo.png",
            "contact_email": "contact@polytechnique.cm",
            "application_deadline": "July 15, 2026",
            "rolling_admission": False,
            "city": "Yaoundé",
            "institution_type": "public",
            "data_source_url": "https://polytechnique.cm",
        },
        "programs": [
            {
                "field_of_study": "Computer Engineering & Artificial Intelligence",
                "degree_type": "Engineering Diploma (Master Equiv.)",
                "tuition_fee": "50,000 FCFA / year (State tuition)",
                "duration": "5 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive entrance examination (Concours National) open to Bac C/D/TI/E or GCE A-Level Sciences (Math & Physics).",
                "required_documents": "Certified copy of Birth Certificate, Baccalaureat/GCE A-Level slip, Medical certificate of fitness, Concours receipt.",
                "application_deadline": "July 15, 2026",
                "class_size": 75,
                "description": "Elite 5-year engineering cycle encompassing computer architecture, deep learning, embedded robotics, distributed computing, and software systems.",
            },
            {
                "field_of_study": "Telecommunications & Network Engineering",
                "degree_type": "Engineering Diploma (Master Equiv.)",
                "tuition_fee": "50,000 FCFA / year (State tuition)",
                "duration": "5 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive national entrance exam (Concours ENSPY) in Mathematics and Physics.",
                "required_documents": "Concours file, certified transcripts, National ID copy, Birth certificate, 4 passport photos.",
                "application_deadline": "July 15, 2026",
                "class_size": 60,
                "description": "In-depth education covering 5G/6G mobile networks, fiber optics, RF systems, satellite communications, network protocols, and cyber-defense.",
            },
            {
                "field_of_study": "Civil & Environmental Engineering",
                "degree_type": "Engineering Diploma (Master Equiv.)",
                "tuition_fee": "50,000 FCFA / year (State tuition)",
                "duration": "5 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "National competitive entrance examination (Concours) for Bac C, D, E, F4 or GCE A-Level with Math and Physics.",
                "required_documents": "Concours application receipt, certified academic diplomas, medical certificate, birth certificate.",
                "application_deadline": "July 15, 2026",
                "class_size": 80,
                "description": "Structural design, geotechnics, bridge and road construction, hydraulics, smart infrastructure, and sustainable environmental engineering.",
            },
        ],
    },
    {
        "school": {
            "name": "IUSTY (Institut Universitaire et Strategique de l'Estuaire)",
            "location": "Soa / Nsam, Yaounde, Centre Region, Cameroon",
            "description": "Fast-growing university institute offering vocational degrees, professional bachelors, and masters focused on immediate industry employment.",
            "website_url": "https://iusty.com",
            "logo_url": "https://iusty.com/assets/img/logo.png",
            "contact_email": "info@iusty.com",
            "application_deadline": "October 25, 2026",
            "rolling_admission": True,
            "city": "Yaoundé",
            "institution_type": "iup",
            "data_source_url": "https://ictuniversity.edu.cm",
        },
        "programs": [
            {
                "field_of_study": "Software Engineering & Database Administration",
                "degree_type": "Licence Professionnelle",
                "tuition_fee": "450,000 FCFA / year",
                "duration": "3 years (or 1 yr top-up after BTS/HND)",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Baccalaureat (all series) or GCE A-Level (min 2 papers), or HND/BTS for direct 3rd year entry.",
                "required_documents": "Copy of National ID card, birth certificate, certified copies of high school diplomas, 2 passport photos.",
                "application_deadline": "October 25, 2026",
                "class_size": 50,
                "description": "Practical, market-oriented degree covering backend APIs, relational & NoSQL databases, mobile applications, and cloud devops.",
            },
            {
                "field_of_study": "Accounting, Audit & Financial Control",
                "degree_type": "Licence Professionnelle",
                "tuition_fee": "420,000 FCFA / year",
                "duration": "3 years",
                "language_of_instruction": "French",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Baccalaureat G2/B/C/D or GCE A-Level with passes in Economics or Accounting.",
                "required_documents": "Certified high school diploma, birth certificate, transcript of records, 2 passport size photos.",
                "application_deadline": "October 25, 2026",
                "class_size": 70,
                "description": "Comprehensive OHADA accounting standards, corporate taxation, statutory auditing, management control, and financial reporting.",
            },
            {
                "field_of_study": "Logistics & Transport Management",
                "degree_type": "HND (Higher National Diploma)",
                "tuition_fee": "380,000 FCFA / year",
                "duration": "2 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Baccalaureat (any series) or GCE A-Level (minimum 2 papers).",
                "required_documents": "High school diploma copy, birth certificate, application form, 2 passport photos.",
                "application_deadline": "October 25, 2026",
                "class_size": 60,
                "description": "Supply chain optimization, freight forwarding, customs clearance, warehouse management, and international trade operations.",
            },
        ],
    },
    {
        "school": {
            "name": "Messassi Institute of Science and Technology (MIST)",
            "location": "Dispensaire Messassi, Yaounde, Centre Region, Cameroon",
            "description": "Specialized polytechnic institute known for rigorous hands-on technical training, biomedical technologies, engineering, and digital entrepreneurship.",
            "website_url": "https://mist.cm",
            "logo_url": "https://mist.cm/assets/images/mist-logo.png",
            "contact_email": "admissions@mist.cm",
            "application_deadline": "November 05, 2026",
            "rolling_admission": True,
            "city": "Yaoundé",
            "institution_type": "ipes",
            "data_source_url": "https://ictuniversity.edu.cm",
        },
        "programs": [
            {
                "field_of_study": "Biomedical Engineering & Hospital Equipment Maintenance",
                "degree_type": "Bachelor of Technology",
                "tuition_fee": "650,000 FCFA / year",
                "duration": "3 years",
                "language_of_instruction": "English",
                "delivery_mode": "On-Campus",
                "admission_requirements": "GCE Advanced Level in Sciences (Physics, Biology, Chemistry, or Math) or Bac C/D/F5.",
                "required_documents": "Certified GCE/Bac transcripts, copy of Birth Certificate, National ID, Medical fitness certificate.",
                "application_deadline": "November 05, 2026",
                "class_size": 40,
                "description": "Specialized technical program bridging healthcare and engineering: maintenance of diagnostic imaging, patient monitors, and hospital robotics.",
            },
            {
                "field_of_study": "Electrical Power Systems & Renewable Energy",
                "degree_type": "Bachelor of Technology",
                "tuition_fee": "580,000 FCFA / year",
                "duration": "3 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "GCE A-Level Sciences (Math & Physics) or Bac C, E, F3.",
                "required_documents": "Certified high school credentials, Birth Certificate, National ID card copy, 2 passport photos.",
                "application_deadline": "November 05, 2026",
                "class_size": 50,
                "description": "Solar PV design, mini-grid electrification, industrial electrical installations, high-voltage networks, and energy efficiency systems.",
            },
            {
                "field_of_study": "Computer Systems & Network Security",
                "degree_type": "HND (Higher National Diploma)",
                "tuition_fee": "480,000 FCFA / year",
                "duration": "2 years",
                "language_of_instruction": "English",
                "delivery_mode": "On-Campus",
                "admission_requirements": "GCE Advanced Level (min 2 papers) or Baccalaureat C/D/TI.",
                "required_documents": "Certified copies of GCE/Bac, Birth certificate, 2 photos, National ID card.",
                "application_deadline": "November 05, 2026",
                "class_size": 45,
                "description": "Practical 2-year state HND covering Linux administration, Cisco routing and switching, firewall configuration, and client-server networks.",
            },
        ],
    },
{
        "school": {
            "name": "Université de Yaoundé I (UY1)",
            "location": "Ngoa-Ekellé, Yaoundé, Centre Region, Cameroon",
            "city": "Yaoundé",
            "institution_type": "public",
            "description": "The mother university of Cameroon, established in 1962, hosting faculties of Science, Arts & Human Sciences, Medicine & Biomedical Sciences (FMSB), and the Higher Teacher Training College (ENS Yaoundé).",
            "website_url": "https://uy1.uninet.cm",
            "logo_url": "https://uy1.uninet.cm/wp-content/uploads/2021/03/logo-uy1.png",
            "contact_email": None,
            "application_deadline": None,
            "rolling_admission": False,
            "data_source_url": "https://uy1.uninet.cm",
            "last_verified_at": now,
        },
        "programs": [
            {
                "field_of_study": "Informatique",
                "degree_type": "Licence",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Baccalauréat C/D/TI or GCE A-Level Science passes.",
                "required_documents": "Certified copy of Birth Certificate, Baccalauréat/GCE A-Level transcript, National ID card copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Foundational curriculum in algorithms, data structures, software development, database systems, and networking at the Faculté des Sciences.",
            },
            {
                "field_of_study": "Mathématiques",
                "degree_type": "Licence",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Baccalauréat C/E or GCE A-Level Mathematics.",
                "required_documents": "Academic transcripts, Bac/GCE slip, National ID, Birth certificate.",
                "application_deadline": None,
                "class_size": None,
                "description": "Rigorous undergraduate training in pure and applied mathematics, algebra, analysis, probability, and statistics.",
            },
            {
                "field_of_study": "Physique",
                "degree_type": "Licence",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Baccalauréat C/D or GCE A-Level Physics and Math.",
                "required_documents": "Academic transcripts, Bac/GCE slip, National ID, Birth certificate.",
                "application_deadline": None,
                "class_size": None,
                "description": "Curriculum encompassing classical mechanics, thermodynamics, optics, electromagnetism, and modern quantum physics.",
            },
            {
                "field_of_study": "Biosciences (Biologie Animale et Végétale)",
                "degree_type": "Licence",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Baccalauréat C/D or GCE A-Level Biology and Chemistry.",
                "required_documents": "Academic transcripts, Bac/GCE slip, National ID, Birth certificate.",
                "application_deadline": None,
                "class_size": None,
                "description": "Comprehensive biological sciences curriculum covering zoology, botany, physiology, genetics, and ecology.",
            },
            {
                "field_of_study": "Informatique Fondamentale et Appliquée",
                "degree_type": "Master",
                "tuition_fee": None,
                "duration": "2 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Licence en Informatique or recognised equivalent with satisfactory academic standing.",
                "required_documents": "Certified degree certificate, official transcripts, CV, Motivation letter, ID copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Advanced graduate specialization in distributed computing, artificial intelligence, cybersecurity, and data modeling.",
            },
            {
                "field_of_study": "Médecine Générale",
                "degree_type": "Doctorat en Médecine",
                "tuition_fee": None,
                "duration": "7 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive entrance examination (Concours National Unique MINESUP) open to Baccalauréat C/D or GCE A-Level Sciences.",
                "required_documents": "Concours registration slip, Bac/GCE certificate, Birth certificate, Medical fitness certificate.",
                "application_deadline": None,
                "class_size": None,
                "description": "Prestigious state medical training at the Faculté de Médecine et des Sciences Biomédicales (FMSB - CUSS) covering pre-clinical sciences, clinical clerkships, and medical research.",
            },
            {
                "field_of_study": "Pharmacie",
                "degree_type": "Doctorat en Pharmacie",
                "tuition_fee": None,
                "duration": "6 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive entrance examination (Concours National Unique MINESUP) open to Bac C/D or GCE A-Level Sciences.",
                "required_documents": "Concours dossier, certified transcripts, National ID copy, Birth certificate.",
                "application_deadline": None,
                "class_size": None,
                "description": "Comprehensive pharmaceutical curriculum training clinical pharmacists, industrial formulation experts, and drug regulatory officers.",
            },
            {
                "field_of_study": "Odonto-Stomatologie (Chirurgie Dentaire)",
                "degree_type": "Doctorat en Chirurgie Dentaire",
                "tuition_fee": None,
                "duration": "6 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive entrance exam (Concours National Unique MINESUP) for health science candidates.",
                "required_documents": "Concours file, certified academic certificates, Medical certificate.",
                "application_deadline": None,
                "class_size": None,
                "description": "Clinical and surgical training in oral pathology, dental surgery, prosthetics, and public dental health at FMSB.",
            },
            {
                "field_of_study": "Professeur de l'Enseignement Secondaire (DIPES I)",
                "degree_type": "DIPES I",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive national entrance examination (Concours ENS Yaoundé) open to Baccalauréat or GCE A-Level holders.",
                "required_documents": "Concours dossier, certified Bac/GCE transcript, Birth certificate, Certificate of non-conviction.",
                "application_deadline": None,
                "class_size": None,
                "description": "Elite secondary school teacher training at École Normale Supérieure (ENS) de Yaoundé across sciences, humanities, and languages.",
            },
            {
                "field_of_study": "Professeur de l'Enseignement Secondaire (DIPES II)",
                "degree_type": "DIPES II",
                "tuition_fee": None,
                "duration": "2 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive national entrance exam (Concours ENS Yaoundé) open to Bachelor / Licence degree holders.",
                "required_documents": "Concours file, certified Licence degree, official transcripts, National ID copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Advanced second-grade teacher training at ENS Yaoundé for high school and teacher college instructors.",
            },
            {
                "field_of_study": "Sociologie",
                "degree_type": "Licence",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "French",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Baccalauréat A/B/C/D or GCE A-Level.",
                "required_documents": "Certified Bac/GCE slip, National ID, Birth certificate.",
                "application_deadline": None,
                "class_size": None,
                "description": "Study of social structures, sociological theories, development sociology, and qualitative/quantitative research methods at FALSH.",
            },
            {
                "field_of_study": "Études Bilingues (Français - Anglais)",
                "degree_type": "Licence",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Baccalauréat A with English or GCE A-Level with French.",
                "required_documents": "Academic transcripts, Bac/GCE slip, National ID, Birth certificate.",
                "application_deadline": None,
                "class_size": None,
                "description": "Bilingual immersion program in translation, linguistics, and literature in French and English.",
            },
            {
                "field_of_study": "Sciences de l'Éducation",
                "degree_type": "Licence",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "French",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Baccalauréat or GCE A-Level.",
                "required_documents": "Academic certificates, ID card copy, Birth certificate.",
                "application_deadline": None,
                "class_size": None,
                "description": "Undergraduate program covering pedagogy, educational psychology, curriculum planning, and education management at FSE.",
            },
        ],
    },
    {
        "school": {
            "name": "Université de Yaoundé II (UY2)",
            "location": "Soa, Yaoundé, Centre Region, Cameroon",
            "city": "Yaoundé",
            "institution_type": "public",
            "description": "Cameroon's state university specializing in legal, political, economic, and managerial sciences, comprising the Faculty of Legal and Political Sciences (FSJP) and the Faculty of Economics and Management (FSEG).",
            "website_url": "https://site.univ-yaounde2.org",
            "logo_url": None,
            "contact_email": None,
            "application_deadline": None,
            "rolling_admission": False,
            "data_source_url": "https://site.univ-yaounde2.org",
            "last_verified_at": now,
        },
        "programs": [
            {
                "field_of_study": "Droit Privé Fondamental",
                "degree_type": "Licence",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "French",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Baccalauréat A/B/C/D or GCE A-Level.",
                "required_documents": "Certified Bac/GCE slip, Birth certificate, National ID card copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Undergraduate curriculum at FSJP covering civil law, contract law, commercial law, criminal law, and civil procedure.",
            },
            {
                "field_of_study": "Droit Public",
                "degree_type": "Licence",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "French",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Baccalauréat A/B/C/D or GCE A-Level.",
                "required_documents": "Certified Bac/GCE slip, Birth certificate, National ID card copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Comprehensive program covering constitutional law, administrative law, public international law, and public finance.",
            },
            {
                "field_of_study": "Science Politique",
                "degree_type": "Licence",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "French",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Baccalauréat A/B/C/D or GCE A-Level.",
                "required_documents": "Certified Bac/GCE slip, Birth certificate, National ID card copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Study of political regimes, international relations, political sociology, public policies, and political theories at FSJP.",
            },
            {
                "field_of_study": "English Common Law",
                "degree_type": "Bachelor of Laws (LL.B)",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "English",
                "delivery_mode": "On-Campus",
                "admission_requirements": "GCE Advanced Level with minimum 2 passes or Baccalauréat.",
                "required_documents": "GCE A-Level slip, Birth Certificate, National ID copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Full Common Law curriculum at the English section of FSJP covering law of contract, torts, equity, criminal law, and constitutional law.",
            },
            {
                "field_of_study": "Sciences Économiques - Analyse et Politique Économiques",
                "degree_type": "Licence",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "French",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Baccalauréat C/D/B/E or GCE A-Level.",
                "required_documents": "Certified Bac/GCE slip, Birth certificate, National ID card copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Undergraduate economics program at FSEG covering microeconomics, macroeconomics, econometrics, public finance, and development economics.",
            },
            {
                "field_of_study": "Sciences de Gestion - Comptabilité et Finance",
                "degree_type": "Licence",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "French",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Baccalauréat C/D/B/G2 or GCE A-Level with Math/Accounting.",
                "required_documents": "Certified Bac/GCE slip, Birth certificate, National ID card copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Management science program focusing on corporate finance, accounting, taxation, and business administration.",
            },
            {
                "field_of_study": "Droit des Affaires et Fiscalité",
                "degree_type": "Master",
                "tuition_fee": None,
                "duration": "2 years",
                "language_of_instruction": "French",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Licence en Droit Privé with satisfactory academic record.",
                "required_documents": "Certified Licence certificate, official transcripts, CV, Motivation letter, ID copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Postgraduate specialization in OHADA business law, corporate tax law, arbitration, banking law, and contract drafting.",
            },
            {
                "field_of_study": "Économie et Finance Internationales",
                "degree_type": "Master",
                "tuition_fee": None,
                "duration": "2 years",
                "language_of_instruction": "French",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Licence en Sciences Économiques or equivalent.",
                "required_documents": "Certified Licence degree, transcripts, CV, research proposal / motivation letter.",
                "application_deadline": None,
                "class_size": None,
                "description": "Master's program focusing on international trade, monetary economics, exchange rates, econometric modeling, and economic policy.",
            },
        ],
    },
    {
        "school": {
            "name": "Institut des Relations Internationales du Cameroun (IRIC)",
            "location": "Obili, Yaoundé, Centre Region, Cameroon",
            "city": "Yaoundé",
            "institution_type": "public",
            "description": "Specialized postgraduate institute of the University of Yaoundé II, dedicated to international diplomacy, multilateral cooperation, international economics, and diplomacy since 1971.",
            "website_url": "https://www.iricuy2.com",
            "logo_url": None,
            "contact_email": None,
            "application_deadline": None,
            "rolling_admission": False,
            "data_source_url": "https://www.iricuy2.com",
            "last_verified_at": now,
        },
        "programs": [
            {
                "field_of_study": "Diplomatie",
                "degree_type": "Master Professionnel",
                "tuition_fee": None,
                "duration": "2 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive national entrance examination (Concours National MINESUP/MINREX) open to Bachelor/Licence degree holders in Law, Political Science, or Humanities.",
                "required_documents": "Concours registration file, certified copy of Bachelor/Licence degree, transcripts, Birth certificate, Certificate of non-conviction.",
                "application_deadline": None,
                "class_size": None,
                "description": "Flagship diplomatic training preparing ambassadors, plenipotentiaries, and international civil servants in bilateral negotiations, diplomatic protocol, and geopolitics.",
            },
            {
                "field_of_study": "Droit International Économique",
                "degree_type": "Master Professionnel",
                "tuition_fee": None,
                "duration": "2 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive entrance examination open to Licence/Bachelor holders in Law or Economics.",
                "required_documents": "Concours registration dossier, certified transcripts, National ID copy, Birth certificate.",
                "application_deadline": None,
                "class_size": None,
                "description": "Specialized program in international investment law, WTO trade agreements, dispute settlement, and regional economic treaties.",
            },
            {
                "field_of_study": "Contentieux International",
                "degree_type": "Master Professionnel",
                "tuition_fee": None,
                "duration": "2 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive entrance exam open to Licence in Law holders.",
                "required_documents": "Concours file, certified degree certificate, official transcripts, ID copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Advanced training in international litigation, international court proceedings (ICJ, ICC, arbitration courts), and state responsibility.",
            },
            {
                "field_of_study": "Banque - Monnaie - Contentieux International",
                "degree_type": "Master Professionnel",
                "tuition_fee": None,
                "duration": "2 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive entrance exam open to Bachelor/Licence in Law, Economics, or Management.",
                "required_documents": "Concours dossier, certified academic documents, Birth certificate.",
                "application_deadline": None,
                "class_size": None,
                "description": "Curriculum at the intersection of international monetary law, central banking, cross-border financial regulation, and debt litigation.",
            },
            {
                "field_of_study": "Communication et Action Publique Internationale",
                "degree_type": "Master Professionnel",
                "tuition_fee": None,
                "duration": "2 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive entrance exam open to Bachelor/Licence holders in any relevant discipline.",
                "required_documents": "Concours dossier, certified degree, transcripts, National ID copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Training in international public diplomacy, strategic communication for international organizations, advocacy, and crisis communication.",
            },
        ],
    },
    {
        "school": {
            "name": "École Supérieure des Sciences et Techniques de l'Information et de la Communication (ESSTIC)",
            "location": "Ngoa-Ekellé, Yaoundé, Centre Region, Cameroon",
            "city": "Yaoundé",
            "institution_type": "public",
            "description": "Sub-regional public institution affiliated with University of Yaoundé II, training journalists, communications specialists, documentalists, and publishing professionals across Central Africa.",
            "website_url": "https://esstic.cm",
            "logo_url": None,
            "contact_email": None,
            "application_deadline": None,
            "rolling_admission": False,
            "data_source_url": "https://esstic.cm",
            "last_verified_at": now,
        },
        "programs": [
            {
                "field_of_study": "Journalisme",
                "degree_type": "Licence Professionnelle",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive national entrance examination (Concours ESSTIC - MINESUP) open to holders of Baccalauréat (all series) or GCE A-Level.",
                "required_documents": "Concours application form, certified copy of Bac/GCE slip, Birth certificate, Medical certificate, 4 passport photos.",
                "application_deadline": None,
                "class_size": None,
                "description": "Practical and theoretical training in print journalism, radio broadcasting, television production, investigative reporting, digital media, and media ethics.",
            },
            {
                "field_of_study": "Communication des Organisations",
                "degree_type": "Licence Professionnelle",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive national entrance examination open to Baccalauréat or GCE A-Level holders.",
                "required_documents": "Concours application file, certified Bac/GCE transcript, Birth certificate, National ID card copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Training in corporate communications, public relations, internal communication, event management, and institutional branding.",
            },
            {
                "field_of_study": "Publicité",
                "degree_type": "Licence Professionnelle",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive national entrance exam open to Baccalauréat or GCE A-Level holders.",
                "required_documents": "Concours application file, certified Bac/GCE slip, Birth certificate, National ID copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Curriculum focusing on advertising strategy, creative copywriting, media planning, brand identity, and digital advertising campaigns.",
            },
            {
                "field_of_study": "Édition et Arts Graphiques",
                "degree_type": "Licence Professionnelle",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive national entrance exam open to Baccalauréat or GCE A-Level holders.",
                "required_documents": "Concours file, certified academic certificates, Birth certificate, ID copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Specialized training in book publishing, desktop publishing (PAO), typography, digital editorial workflows, and print production.",
            },
            {
                "field_of_study": "Information Documentaire",
                "degree_type": "Licence Professionnelle",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive national entrance exam open to Baccalauréat or GCE A-Level holders.",
                "required_documents": "Concours file, certified Bac/GCE transcript, Birth certificate, ID card copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Training in library science, archiving, documentary research, digital record management, and information databases.",
            },
        ],
    },
    {
        "school": {
            "name": "École Nationale Supérieure des Travaux Publics (ENSTP)",
            "location": "Centre Ville, Yaoundé, Centre Region, Cameroon",
            "city": "Yaoundé",
            "institution_type": "public",
            "description": "Cameroon's premier public engineering institution under the Ministry of Public Works, training elite Civil, Environmental, and Topographic engineers in academic partnership with the University of Padua (Italy).",
            "website_url": "https://www.enstp.cm",
            "logo_url": "https://enstp.cm/wp-content/uploads/2020/04/android-chrome-192x192-1.png",
            "contact_email": None,
            "application_deadline": None,
            "rolling_admission": False,
            "data_source_url": "https://www.enstp.cm",
            "last_verified_at": now,
        },
        "programs": [
            {
                "field_of_study": "Génie Civil",
                "degree_type": "Diplôme d'Ingénieur de Conception",
                "tuition_fee": None,
                "duration": "5 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive national entrance examination open to Baccalauréat C/D/E/TI or GCE A-Level in Mathematics and Physics.",
                "required_documents": "Concours dossier, certified copy of Bac/GCE slip, Birth certificate, Medical certificate, 4 photos.",
                "application_deadline": None,
                "class_size": None,
                "description": "5-year engineering cycle delivered in academic partnership with University of Padua (Italy), covering structural engineering, bridges, highway engineering, geotechnics, and hydraulics.",
            },
            {
                "field_of_study": "Génie de l'Environnement",
                "degree_type": "Diplôme d'Ingénieur de Conception",
                "tuition_fee": None,
                "duration": "5 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive national entrance exam open to Bac C/D/E or GCE A-Level Sciences.",
                "required_documents": "Concours file, certified academic transcripts, Birth certificate, ID card copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Specialized engineering program covering environmental impact assessments, water treatment, waste management, and sustainable civil infrastructure.",
            },
            {
                "field_of_study": "Topographie et Cadastre",
                "degree_type": "Diplôme d'Ingénieur des Travaux",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive national entrance exam open to Bac C/D/E/F4 or GCE A-Level.",
                "required_documents": "Concours dossier, certified Bac/GCE slip, Birth certificate.",
                "application_deadline": None,
                "class_size": None,
                "description": "Training surveyors and topographic engineers in geodesic surveying, photogrammetry, GIS systems, and cadastral mapping.",
            },
            {
                "field_of_study": "Technicien Supérieur des Travaux Publics",
                "degree_type": "Diplôme de Technicien Supérieur",
                "tuition_fee": None,
                "duration": "2 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive national entrance exam open to Baccalauréat (all series) or GCE A-Level.",
                "required_documents": "Concours file, certified academic certificates, ID copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Vocational technical cycle training site supervisors in civil engineering, rural engineering, urban planning, and topographic surveying.",
            },
        ],
    },
    {
        "school": {
            "name": "École Nationale Supérieure des Postes, des Télécommunications et des TIC (SUP'PTIC)",
            "location": "Ngoa-Ekellé, Yaoundé, Centre Region, Cameroon",
            "city": "Yaoundé",
            "institution_type": "public",
            "description": "Public technological higher institution under the Ministry of Posts and Telecommunications, training engineers, technicians, and managers in telecommunications, cybersecurity, postal finance, and digital networks.",
            "website_url": "https://e-supptic.cm",
            "logo_url": None,
            "contact_email": None,
            "application_deadline": None,
            "rolling_admission": False,
            "data_source_url": "https://e-supptic.cm",
            "last_verified_at": now,
        },
        "programs": [
            {
                "field_of_study": "Ingénieur des Télécommunications",
                "degree_type": "Diplôme d'Ingénieur de Conception",
                "tuition_fee": None,
                "duration": "5 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive national entrance examination (Concours MINPOSTEL/MINESUP) open to Baccalauréat C/D/E/TI or GCE A-Level in Science subjects (Math and Physics).",
                "required_documents": "Concours registration file, certified copy of Bac/GCE slip, Birth certificate, Medical certificate, 4 passport photos.",
                "application_deadline": None,
                "class_size": None,
                "description": "Elite engineering curriculum in mobile networks (4G/5G), optical communications, radio propagation, network architecture, and telecommunications security.",
            },
            {
                "field_of_study": "Ingénieur des Travaux de Télécommunications",
                "degree_type": "Diplôme d'Ingénieur des Travaux",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive national entrance examination open to Bac C/D/E/TI or GCE A-Level Sciences.",
                "required_documents": "Concours application dossier, certified transcripts, National ID copy, Birth certificate.",
                "application_deadline": None,
                "class_size": None,
                "description": "Hands-on technological engineering program covering network deployment, transmission systems, IP routing, and telecom infrastructure maintenance.",
            },
            {
                "field_of_study": "Management des Télécommunications et TIC (Premier Cycle)",
                "degree_type": "Licence Professionnelle",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive national entrance exam open to Baccalauréat (all series) or GCE A-Level.",
                "required_documents": "Concours file, certified Bac/GCE slip, Birth certificate, ID card copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Management program tailored for the ICT sector, encompassing telecom economics, digital marketing, postal financial services, and ICT project management.",
            },
            {
                "field_of_study": "Management des Télécommunications et TIC (Second Cycle)",
                "degree_type": "Master Professionnel",
                "tuition_fee": None,
                "duration": "2 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive entrance examination open to Bachelor/Licence degree holders in Management, Economics, or related fields.",
                "required_documents": "Concours registration file, certified degree certificate, transcripts, ID card copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Advanced postgraduate program in telecom regulation, spectrum management, strategic management of telecom operators, and digital transformation.",
            },
        ],
    },
    {
        "school": {
            "name": "Université Catholique d'Afrique Centrale (UCAC)",
            "location": "Ekounou & Nkolbisson Campuses, Yaoundé, Centre Region, Cameroon",
            "city": "Yaoundé",
            "institution_type": "ipes",
            "description": "Sub-regional private Catholic university established by the Association of Episcopal Conferences of the Central African Region (ACERAC), recognized across Africa for academic excellence in social sciences, management, law, theology, and philosophy.",
            "website_url": "https://ucac-icy.net",
            "logo_url": None,
            "contact_email": None,
            "application_deadline": None,
            "rolling_admission": False,
            "data_source_url": "https://ucac-icy.net",
            "last_verified_at": now,
        },
        "programs": [
            {
                "field_of_study": "Gestion des Ressources Humaines",
                "degree_type": "Licence",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "French",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive entrance examination (Concours d'entrée UCAC) open to Baccalauréat (all series) or GCE A-Level.",
                "required_documents": "Application form, certified copy of Bac/GCE slip, Birth certificate, 2 recommendation letters, 2 photos.",
                "application_deadline": None,
                "class_size": None,
                "description": "Rigorous undergraduate training at the Faculté de Sciences Sociales et de Gestion (FSSG) in HR management, labor law, organizational sociology, and talent acquisition.",
            },
            {
                "field_of_study": "Administration des Entreprises",
                "degree_type": "Licence",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "French",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive entrance examination open to Baccalauréat or GCE A-Level holders.",
                "required_documents": "Application dossier, academic transcripts, Bac/GCE certificate, Birth certificate.",
                "application_deadline": None,
                "class_size": None,
                "description": "General business administration program covering corporate strategy, operations management, accounting, and business economics.",
            },
            {
                "field_of_study": "Comptabilité et Finance",
                "degree_type": "Licence",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "French",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive entrance exam open to Bac C/D/B/G2 or GCE A-Level with Math/Accounting.",
                "required_documents": "Application dossier, certified transcripts, National ID copy, Birth certificate.",
                "application_deadline": None,
                "class_size": None,
                "description": "Undergraduate program in financial accounting, corporate financial analysis, management control, and taxation.",
            },
            {
                "field_of_study": "Droit Privé et Sciences Juridiques",
                "degree_type": "Licence",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "French",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive entrance examination at Campus Nkolbisson open to Baccalauréat A/B/C/D or GCE A-Level.",
                "required_documents": "Application file, certified Bac/GCE certificate, Birth certificate, ID card copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Comprehensive legal curriculum covering civil law, commercial and company law, contract obligations, and judicial organization.",
            },
            {
                "field_of_study": "Droit des Affaires et Fiscalité",
                "degree_type": "Master",
                "tuition_fee": None,
                "duration": "2 years",
                "language_of_instruction": "French",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Written competitive exam and dossier evaluation open to Bachelor/Licence in Law holders.",
                "required_documents": "Certified degree certificate, transcripts of all university years, CV, Motivation letter, 2 reference letters.",
                "application_deadline": None,
                "class_size": None,
                "description": "Elite postgraduate specialization in OHADA corporate law, international taxation, banking and securities law, and commercial arbitration.",
            },
            {
                "field_of_study": "Banque et Marchés Financiers",
                "degree_type": "Master",
                "tuition_fee": None,
                "duration": "2 years",
                "language_of_instruction": "French",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Written competitive exam and dossier review open to Licence in Finance, Economics, or Management.",
                "required_documents": "Certified Licence certificate, official transcripts, CV, Motivation letter, ID copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Postgraduate training in asset management, financial risk analysis, capital markets regulation, and investment banking in CEMAC.",
            },
        ],
    },
    {
        "school": {
            "name": "PKFokam Institute of Excellence",
            "location": "Tradex Emana, Yaoundé, Centre Region, Cameroon",
            "city": "Yaoundé",
            "institution_type": "ipes",
            "description": "Authorized by MINESUP (Order N° 07/0010/MINESUP). An incubator of excellence founded to prepare African leaders through rigorous, marketplace-relevant curricula in engineering, technology, economics, and business in partnership with international institutions.",
            "website_url": "https://www.pkfinstitute.com",
            "logo_url": "https://pkfie.com/kfokam-institute-logo.png",
            "contact_email": None,
            "application_deadline": "January 8, 2027",
            "rolling_admission": False,
            "data_source_url": "https://www.pkfinstitute.com",
            "last_verified_at": now,
        },
        "programs": [
            {
                "field_of_study": "Computer & Software Engineering",
                "degree_type": "Bachelor of Science",
                "tuition_fee": None,
                "duration": "4 years",
                "language_of_instruction": "English",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive entrance examination and oral interview. Open to GCE A-Level Sciences (minimum 2 papers with C in Math/Physics) or Baccalauréat C/D/TI/E.",
                "required_documents": "GCE A-Level / Baccalauréat transcript, Copy of National ID / Passport, 2 passport photos, Birth Certificate, Application form.",
                "application_deadline": "January 8, 2027",
                "class_size": None,
                "description": "Industry-aligned engineering program covering algorithms, software architectures, distributed cloud computing, artificial intelligence, and embedded systems.",
            },
            {
                "field_of_study": "Information Technology",
                "degree_type": "Bachelor of Science",
                "tuition_fee": None,
                "duration": "4 years",
                "language_of_instruction": "English",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive entrance examination and oral interview. Open to GCE A-Level or Baccalauréat.",
                "required_documents": "Academic transcripts, certified certificates, Copy of ID, Birth certificate.",
                "application_deadline": "January 8, 2027",
                "class_size": None,
                "description": "Undergraduate program in enterprise networking, system administration, cybersecurity operations, web architectures, and cloud services.",
            },
            {
                "field_of_study": "Mechanical Engineering Technology",
                "degree_type": "Bachelor of Science",
                "tuition_fee": None,
                "duration": "4 years",
                "language_of_instruction": "English",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive entrance examination and oral interview. Open to GCE A-Level Sciences or Bac C/D/E.",
                "required_documents": "Certified academic transcripts, GCE/Bac slip, Birth certificate, ID copy.",
                "application_deadline": "January 8, 2027",
                "class_size": None,
                "description": "Practical hands-on training in mechanical design, thermodynamics, materials engineering, CAD/CAM, and industrial manufacturing systems.",
            },
            {
                "field_of_study": "Mechatronics",
                "degree_type": "Bachelor of Science",
                "tuition_fee": None,
                "duration": "4 years",
                "language_of_instruction": "English",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive entrance examination and oral interview. Open to GCE A-Level Sciences or Bac C/D/E.",
                "required_documents": "Certified academic certificates, ID copy, Birth certificate.",
                "application_deadline": "January 8, 2027",
                "class_size": None,
                "description": "Multidisciplinary program integrating mechanical systems, electronic control, sensor technology, robotics, and industrial automation.",
            },
            {
                "field_of_study": "Electrical & Telecommunications Engineering",
                "degree_type": "Bachelor of Science",
                "tuition_fee": None,
                "duration": "4 years",
                "language_of_instruction": "English",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive entrance examination and oral interview. Open to GCE A-Level Sciences or Bac C/D/E.",
                "required_documents": "Certified academic certificates, ID copy, Birth certificate.",
                "application_deadline": "January 8, 2027",
                "class_size": None,
                "description": "Comprehensive engineering curriculum in electrical power systems, signal processing, digital communications, RF systems, and wireless networks.",
            },
            {
                "field_of_study": "Economics",
                "degree_type": "Bachelor of Science",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "English",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive entrance exam and oral interview. Open to GCE A-Level (Math/Economics) or Bac B/C/D.",
                "required_documents": "GCE/Bac certificate, official transcripts, National ID copy, Birth certificate.",
                "application_deadline": "January 8, 2027",
                "class_size": None,
                "description": "Rigorous undergraduate program in quantitative economics, financial econometric modeling, monetary systems, and African economic development.",
            },
            {
                "field_of_study": "Management",
                "degree_type": "Bachelor of Science",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "English",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive entrance exam and oral interview. Open to GCE A-Level or Baccalauréat.",
                "required_documents": "GCE/Bac slip, transcripts, National ID copy, Birth certificate.",
                "application_deadline": "January 8, 2027",
                "class_size": None,
                "description": "Leadership and business management curriculum covering operations, finance, strategic planning, human capital, and entrepreneurship.",
            },
            {
                "field_of_study": "Master of Business Administration (MBA)",
                "degree_type": "MBA",
                "tuition_fee": None,
                "duration": "2 years",
                "language_of_instruction": "English",
                "delivery_mode": "On-Campus",
                "admission_requirements": "KFokam Business School admission session: Bachelor's degree in any discipline with relevant professional experience and interview.",
                "required_documents": "Certified degree certificate, official transcripts, professional CV, Statement of Purpose, 2 recommendation letters.",
                "application_deadline": "October 1, 2026",
                "class_size": None,
                "description": "Executive graduate curriculum designed to cultivate visionary business leaders, entrepreneurs, and global managers.",
            },
        ],
    },
    {
        "school": {
            "name": "Institut Universitaire Siantou (IUS)",
            "location": "Coron & Mvog-Mbi Campuses, Yaoundé, Centre Region, Cameroon",
            "city": "Yaoundé",
            "institution_type": "iup",
            "description": "Pioneer private higher education institution in Cameroon founded in 1991, offering nationwide recognized vocational and professional programs in commerce, management, technology, and engineering.",
            "website_url": "https://siantou-univ.com",
            "logo_url": None,
            "contact_email": None,
            "application_deadline": None,
            "rolling_admission": True,
            "data_source_url": "https://siantou-univ.com",
            "last_verified_at": now,
        },
        "programs": [
            {
                "field_of_study": "Informatique de Gestion (Génie Logiciel & Réseaux)",
                "degree_type": "BTS",
                "tuition_fee": None,
                "duration": "2 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Baccalauréat C/D/TI/E or GCE A-Level in Science subjects.",
                "required_documents": "Certified Bac/GCE slip, Birth certificate, National ID card copy, Registration form.",
                "application_deadline": None,
                "class_size": None,
                "description": "National vocational curriculum leading to the official state BTS diploma, covering programming, database management, web development, and network administration.",
            },
            {
                "field_of_study": "Comptabilité et Gestion des Entreprises (CGE)",
                "degree_type": "BTS",
                "tuition_fee": None,
                "duration": "2 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Baccalauréat (all series) or GCE A-Level.",
                "required_documents": "Certified Bac/GCE certificate, Birth certificate, National ID card copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Comprehensive program preparing students for state examination in financial accounting, cost accounting, corporate taxation, and payroll management.",
            },
            {
                "field_of_study": "Commerce International",
                "degree_type": "BTS",
                "tuition_fee": None,
                "duration": "2 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Baccalauréat or GCE A-Level.",
                "required_documents": "Certified Bac/GCE slip, Birth certificate, ID card copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Training in international trade operations, customs procedures, import-export logistics, and international marketing.",
            },
            {
                "field_of_study": "Gestion des Ressources Humaines",
                "degree_type": "Licence Professionnelle",
                "tuition_fee": None,
                "duration": "1 year",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "BTS, HND, DUT in management or recognized Bac+2 equivalent.",
                "required_documents": "Certified Bac+2 diploma/transcripts, Birth certificate, National ID copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Professional 1-year top-up degree under state university tutelage covering compensation management, labor relations, recruitment, and HR audits.",
            },
            {
                "field_of_study": "Finances et Comptabilité",
                "degree_type": "Licence Professionnelle",
                "tuition_fee": None,
                "duration": "1 year",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "BTS CGE, HND Accounting, or equivalent Bac+2 qualification.",
                "required_documents": "Certified academic transcripts, BTS certificate, ID card copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Professional specialization in financial statement analysis, corporate tax auditing, treasury management, and IFRS standards.",
            },
            {
                "field_of_study": "Finance et Fiscalité",
                "degree_type": "Master Professionnel",
                "tuition_fee": None,
                "duration": "2 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Licence in Finance, Accounting, Economics, or equivalent degree.",
                "required_documents": "Certified Licence diploma, transcripts of all university years, CV, Motivation letter.",
                "application_deadline": None,
                "class_size": None,
                "description": "Advanced training in fiscal engineering, strategic financial planning, corporate restructuring, and financial risk mitigation.",
            },
        ],
    },
    {
        "school": {
            "name": "Institut Saint Jean (ISJ)",
            "location": "Simbock / Etok-Koss, Yaoundé, Centre Region, Cameroon",
            "city": "Yaoundé",
            "institution_type": "ipes",
            "description": "Prestigious Catholic engineering institute under academic tutelage of ENSPY (Université de Yaoundé I) and partnered with Université de Technologie de Troyes (France), training state-recognized and international-grade engineers.",
            "website_url": "https://institutsaintjean.org",
            "logo_url": "https://institutsaintjean.org/favicon.png",
            "contact_email": None,
            "application_deadline": None,
            "rolling_admission": False,
            "data_source_url": "https://institutsaintjean.org",
            "last_verified_at": now,
        },
        "programs": [
            {
                "field_of_study": "Informatique et Systèmes d'Information (ISI)",
                "degree_type": "Diplôme d'Ingénieur",
                "tuition_fee": None,
                "duration": "5 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive written and oral entrance examination. Open to Baccalauréat C/D/TI/E or GCE A-Level Sciences (Mathematics & Physics).",
                "required_documents": "Concours dossier, certified copy of Bac/GCE slip, Birth certificate, National ID card copy, 2 photos.",
                "application_deadline": None,
                "class_size": None,
                "description": "5-year engineering cycle under ENSPY tutelage comprising 2 years integrated preparatory cycle and 3 years specialization in software engineering, enterprise information systems, cloud, and 13 months mandatory internships.",
            },
            {
                "field_of_study": "Systèmes, Réseaux et Télécommunications (SRT)",
                "degree_type": "Diplôme d'Ingénieur",
                "tuition_fee": None,
                "duration": "5 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive entrance examination open to Bac C/D/TI/E or GCE A-Level Sciences.",
                "required_documents": "Concours dossier, certified transcripts, National ID copy, Birth certificate.",
                "application_deadline": None,
                "class_size": None,
                "description": "Engineering cycle training specialists in telecommunications network architectures, cybersecurity, distributed infrastructure, and IoT systems.",
            },
            {
                "field_of_study": "Classes Préparatoires aux Grandes Écoles d'Ingénieurs",
                "degree_type": "Cycle Préparatoire",
                "tuition_fee": None,
                "duration": "2 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Competitive entrance exam open to high-achieving Bac C/D/E or GCE A-Level Science students.",
                "required_documents": "Concours file, certified Bac/GCE slip, Birth certificate, ID card copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Intensive two-year integrated preparatory curriculum in advanced mathematics, physics, computer science, and engineering sciences preparing for the engineering branches.",
            },
        ],
    },
    {
        "school": {
            "name": "Institut Universitaire Agenla Academy",
            "location": "Nsa-Zomo & Bastos, Yaoundé, Centre Region, Cameroon",
            "city": "Yaoundé",
            "institution_type": "iup",
            "description": "Accredited private higher education institute in Yaoundé offering industry-aligned engineering, mining/petroleum, health sciences, and management degree programs under tutelage of Cameroonian public state universities.",
            "website_url": "https://agenlaacademy.com",
            "logo_url": None,
            "contact_email": None,
            "application_deadline": None,
            "rolling_admission": True,
            "data_source_url": "https://agenlaacademy.com",
            "last_verified_at": now,
        },
        "programs": [
            {
                "field_of_study": "Génie Civil",
                "degree_type": "Diplôme d'Ingénieur",
                "tuition_fee": None,
                "duration": "5 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Dossier review or entrance examination open to Baccalauréat C/D/E/F4 or GCE A-Level Sciences.",
                "required_documents": "Application file, certified Bac/GCE transcript, Birth certificate, National ID card copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Complete engineering cycle training construction engineers in building design, geotechnics, bridge construction, and public works.",
            },
            {
                "field_of_study": "Mines, Pétrole et Gaz",
                "degree_type": "Diplôme d'Ingénieur",
                "tuition_fee": None,
                "duration": "5 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Dossier review and entrance exam open to Bac C/D/E or GCE A-Level Sciences.",
                "required_documents": "Application dossier, certified academic documents, National ID copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Specialized curriculum covering geology, drilling engineering, hydrocarbon extraction, mineral processing, and mining environmental management.",
            },
            {
                "field_of_study": "Gestion et Administration des Entreprises",
                "degree_type": "Licence Professionnelle",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Open to Baccalauréat (all series) or GCE A-Level upon dossier review.",
                "required_documents": "Certified Bac/GCE certificate, Birth certificate, National ID copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Undergraduate program in organizational management, business strategy, human resources, and business finance.",
            },
            {
                "field_of_study": "Sciences Infirmières et Médico-Sanitaires",
                "degree_type": "Licence Professionnelle",
                "tuition_fee": None,
                "duration": "3 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Dossier review and entrance evaluation open to Bac C/D or GCE A-Level Sciences.",
                "required_documents": "Academic certificates, Medical fitness certificate, Birth certificate, ID card copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Clinical nursing curriculum encompassing patient care, community health, pharmacology, emergency response, and hospital clinical internships.",
            },
            {
                "field_of_study": "Informatique et Télécommunications",
                "degree_type": "BTS",
                "tuition_fee": None,
                "duration": "2 years",
                "language_of_instruction": "Bilingual (French / English)",
                "delivery_mode": "On-Campus",
                "admission_requirements": "Baccalauréat (all series) or GCE A-Level.",
                "required_documents": "Certified Bac/GCE slip, Birth certificate, ID card copy.",
                "application_deadline": None,
                "class_size": None,
                "description": "Vocational technical degree preparing students for state BTS examination in software maintenance, computer networks, and telecommunications equipment.",
            },
        ],
    },
]

def seed_database():
    db = SessionLocal()
    try:
        print("Clearing existing schools and programs in Neon database...")
        db.execute(text("DELETE FROM programs;"))
        db.execute(text("DELETE FROM schools;"))
        db.commit()

        total_schools = 0
        total_programs = 0

        for item in SEED_DATA:
            school_data = item["school"]
            school = School(**school_data)
            db.add(school)
            db.flush()
            total_schools += 1

            for prog_data in item["programs"]:
                program = Program(school_id=school.id, **prog_data)
                db.add(program)
                total_programs += 1

        db.commit()
        print("Successfully seeded Neon PostgreSQL database!")
        print(f"  - Schools added: {total_schools}")
        print(f"  - Programs added: {total_programs}")
    except Exception as e:
        db.rollback()
        print(f"Error while seeding database: {e}")
        raise
    finally:
        db.close()

if __name__ == "__main__":
    seed_database()
